// Package systemdunit generates and manages the systemd user unit
// that runs `fit-agent serve` in the background.
//
// The unit is installed at $XDG_CONFIG_HOME/systemd/user/fit-agent.service
// (default ~/.config/systemd/user/fit-agent.service) and managed via
// `systemctl --user`. We deliberately stay in the per-user systemd
// instance so the daemon never requires root and follows the user
// session lifecycle.
package systemdunit

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

// UnitName is the canonical filename of the systemd user unit.
const UnitName = "fit-agent.service"

// Params are the substitution values for the unit template.
type Params struct {
	// Binary is the absolute path to the fit-agent executable.
	Binary string
	// Profile, if non-empty, is passed via --profile to serve.
	Profile string
	// ExtraArgs are additional CLI flags appended to the serve command,
	// e.g. ["--quiet-hours", "23:00-06:00"]. Items are quoted
	// individually; spaces inside an item are preserved.
	ExtraArgs []string
	// WorkingDir, if non-empty, sets WorkingDirectory= on the unit.
	WorkingDir string
}

// Validate rejects clearly-broken parameters.
func (p Params) Validate() error {
	if p.Binary == "" {
		return errors.New("binary path is required")
	}
	if !filepath.IsAbs(p.Binary) {
		return fmt.Errorf("binary path must be absolute, got %q", p.Binary)
	}
	return nil
}

const unitTemplate = `# Generated by fit-agent setup-service. Do not edit by hand;
# re-run 'fit-agent setup-service' to regenerate.
[Unit]
Description=fit-agent intervals.icu polling daemon
Documentation=https://github.com/jogvan-k/fit-agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={{.ExecStart}}
{{if .WorkingDir}}WorkingDirectory={{.WorkingDir}}
{{end}}Restart=on-failure
RestartSec=30s
# Backoff bounds: a misconfigured daemon must not hammer the API.
StartLimitIntervalSec=600
StartLimitBurst=5

[Install]
WantedBy=default.target
`

// Render writes the unit file content to w.
func Render(w io.Writer, p Params) error {
	if err := p.Validate(); err != nil {
		return err
	}
	t, err := template.New("unit").Parse(unitTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}
	data := struct {
		ExecStart  string
		WorkingDir string
	}{
		ExecStart:  buildExecStart(p),
		WorkingDir: p.WorkingDir,
	}
	return t.Execute(w, data)
}

// RenderString is a convenience wrapper around [Render].
func RenderString(p Params) (string, error) {
	var buf bytes.Buffer
	if err := Render(&buf, p); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// buildExecStart assembles the ExecStart= line. Arguments are quoted
// with double-quotes so paths containing spaces survive systemd's
// tokenizer.
func buildExecStart(p Params) string {
	parts := []string{quote(p.Binary)}
	if p.Profile != "" {
		parts = append(parts, "--profile", quote(p.Profile))
	}
	parts = append(parts, "serve")
	for _, a := range p.ExtraArgs {
		parts = append(parts, quote(a))
	}
	out := parts[0]
	for _, s := range parts[1:] {
		out += " " + s
	}
	return out
}

// quote double-quotes a token if it contains whitespace or quotes; in
// either case we escape embedded double-quotes. Plain ASCII tokens are
// returned bare for readability.
func quote(s string) string {
	if !needsQuote(s) {
		return s
	}
	escaped := ""
	for _, r := range s {
		if r == '"' || r == '\\' {
			escaped += "\\"
		}
		escaped += string(r)
	}
	return `"` + escaped + `"`
}

func needsQuote(s string) bool {
	if s == "" {
		return true
	}
	for _, r := range s {
		if r == ' ' || r == '\t' || r == '"' || r == '\\' {
			return true
		}
	}
	return false
}

// UnitPath returns the absolute path the unit file is installed to. It
// honors XDG_CONFIG_HOME and falls back to ~/.config.
func UnitPath() (string, error) {
	dir, err := UnitDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, UnitName), nil
}

// UnitDir returns the absolute path to the systemd user unit directory.
func UnitDir() (string, error) {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "systemd", "user"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home dir: %w", err)
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

// Install writes the unit file atomically with mode 0644, creating the
// systemd user directory if needed. It returns the path written.
func Install(p Params) (string, error) {
	body, err := RenderString(p)
	if err != nil {
		return "", err
	}
	dir, err := UnitDir()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create unit dir: %w", err)
	}
	path := filepath.Join(dir, UnitName)
	tmp, err := os.CreateTemp(dir, ".fit-agent-*.service.tmp")
	if err != nil {
		return "", fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()
	if _, err := tmp.WriteString(body); err != nil {
		_ = tmp.Close()
		return "", fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Chmod(0o644); err != nil {
		_ = tmp.Close()
		return "", fmt.Errorf("chmod temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return "", fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return "", fmt.Errorf("rename temp to unit: %w", err)
	}
	return path, nil
}

// Uninstall removes the unit file if present. Returns (true, nil) if a
// file was removed, (false, nil) if there was nothing to remove.
func Uninstall() (bool, error) {
	path, err := UnitPath()
	if err != nil {
		return false, err
	}
	if err := os.Remove(path); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("remove %s: %w", path, err)
	}
	return true, nil
}

// Systemctl runs `systemctl --user <args...>` and returns combined
// output. It is a thin wrapper so the CLI can be tested with a fake.
type Systemctl func(args ...string) ([]byte, error)

// RealSystemctl invokes the real systemctl binary.
func RealSystemctl(args ...string) ([]byte, error) {
	full := append([]string{"--user"}, args...)
	cmd := exec.Command("systemctl", full...)
	return cmd.CombinedOutput()
}
